In [ ]:
#| hide
#| default_exp gpfa

Derivation of the equations to solve the Gaussian Processes Factor Analysis as described in: Yu, B.M., Cunningham, J.P., Santhanam, G., Ryu, S., Shenoy, K.V., Sahani, M., 2008. Gaussian-process factor analysis for low-dimensional single-trial analysis of neural population activity, in: Advances in Neural Information Processing Systems. Curran Associates, Inc.

# Math

## Notation

- $T$  Number of time steps
- $N$  Number of variables observed
- $K$  Number of dimensions of latent variable
- $x_{:,t}$ vector of all the $N$ variables at time $t$, $\in \mathbb{R}^N$
- $x_{n,:}$ vector of the $n$th variable at for time steps in $T$, $\in \mathbb{R}^T$
- $x_{n,t}$ $n$th variable at time $t$, $\in \mathbb{R}$
- $X_M = [x_{:,1}, ... x_{:, T}]$ Matrix with all the $N$ variables at all time steps $T$, $\in \mathbb{R}^{N \times T}$
- $X$ is a vector obtained by "flattening" $X_M$, by putting next to each other all variable at time $t$, $\in \mathbb{R}^{(N \cdot T)}$
- $t$ time step
- $z_{i, t}$ $i$th latent variable at time $t$, $\in \mathbb{R}$
- $Z = [z_1 , ... z_t]$ Vector with $z$ at all time steps in $T$, $\in \mathbb{R}^{K \times T}$



## Gaussian Processes Factor Analysis model

We model the variables in this way
 $$x_{:,t} = \Lambda z_{:,t} + \epsilon $$
where:

- $\Lambda$ is a Factor loading matrix that transforms $z_{:,t}$ into $x_{:,t}$, $\in \mathbb{R}^{N \times K}$
- $\epsilon$ Random noise. The random noise is independent between the different time steps, $\in \mathbb{R}^N$:
    - $p(\epsilon) = \mathcal{N}(0, \psi)$ distribution of noise
    - $\psi$, covariance matrix of noise, it is a diagional matrix, $\in \mathbb{R}^{N \times N}$

The model consider $\langle X \rangle = 0$ (if $X$ doesn't have a 0 mean it can be easily transformed by substracting the mean)

The latent variable $z$ is modelled over time using a Gaussian Process, one process for each dimension $k$
for simplicity we assumed that $z$ has only one dimension ($k = 1$)

$$p(Z) = \mathcal{GP}(0, k(t, t \prime))$$

## Derivation of $p(X)$

$p(x_{:,t}|z_{:,t}) = \mathcal{N}(\Lambda z_{:,t}, \psi)$ is easy to derive and then $p(x_{:,t})$ and $p(z_{:,t}|x_{:,t})$ can be obtained using the rules of Gaussian inference.

However, what is interesting is to have the analytical form of $p(X)$, which models both the relations between $z$ and $x$ and the $z$ and $t$. The likelihood of $p(X)$ can then be maximized to obtain the parameters of the latent transformation and the kernel hyperparameter.

$p(X)$ is a Guassian distribution with $T\cdot N$ dimensions.

$p(X) = \mathcal{N}(\langle X \rangle, \langle X X^T \rangle)$




### Diagonal of the covariance matrix

Let's start with the diagonal of the covariance matrix ($t = t \prime$)

$\langle x_{:,t}x_{:,t}^T \rangle = \langle (\Lambda z_{:,t} + \epsilon_{t})(\Lambda z_{:,t} + \epsilon_{t})^T \rangle$

by multipling the two vectors together we obtain

$\langle x_{:,t}x_{:,t}^T \rangle = \langle \Lambda z_{:,t} z_{:,t}^T \Lambda^T + \Lambda z_{:,t} \epsilon_{t}^T + \epsilon_t \Lambda^T z_{:,t}^T  + \epsilon_t \epsilon_{t}^T \rangle$

The using the linearity of the [expectation](https://www.statlect.com/fundamentals-of-probability/expected-value-properties) we can:

1) transform the expecations of a sum into a sum of expecations
2) move the $\Lambda$ out of the expecation, as it doesn't depend on $z$
3) $\langle z_{:,t} \epsilon_t \rangle = \langle z_{:,t} \rangle \langle \epsilon_t \rangle$ because $z_{:,t}$ and $\epsilon_t$ are independent random variables

$\langle x_{:,t}x_{:,t}^T \rangle = \Lambda \langle z_{:,t} z_{:,t}^T\rangle \Lambda^T + \Lambda \langle z_{:,t} \rangle \langle \epsilon_{t}^T \rangle + \langle \epsilon_{t} \rangle \Lambda^T \langle z_{:,t}^T  \rangle + \langle \epsilon_t \epsilon_{t}^T \rangle$

Then considering that $\langle z_{:,t} \rangle = 0$ and that $\langle \epsilon_t \rangle = 0$
the expression can be simplified as:

$\langle x_{:,t}x_{:,t}^T \rangle = \Lambda \langle z_{:,t} z_{:,t}^T\rangle \Lambda^T + \langle \epsilon_t \epsilon_{t}^T \rangle$

Then substituting:

1) $\langle z_{:,t} z_{:,t}^T\rangle = k(t, t)$ as that is the covariance matrix of the Gaussian process
2) $\langle \epsilon_t \epsilon_t^T \rangle= \psi$

$\langle x_{:,t}x_{:,t}^T \rangle = \Lambda k(t,t)  \Lambda^T + \psi$

### Off-diagonal

similar to the steps of above

$\langle x_{:,t}x_{:,t \prime}^T \rangle = \langle (\Lambda z_{:,t} + \epsilon_{t})(\Lambda z_{:,t \prime} + \epsilon_{t \prime})^T \rangle$

by multipling the two vectors together we obtain

$\langle x_{:,t}x_{:,t \prime}^T \rangle = \langle \Lambda z_{:,t} z_{:,t \prime}^T \Lambda^T + \Lambda z_{:,t} \epsilon_{t \prime}^T + \epsilon_t \Lambda^T z_{:,t \prime}^T  + \epsilon_t \epsilon_{t \prime}^T \rangle$

Then using the linearity of the [expectation](https://www.statlect.com/fundamentals-of-probability/expected-value-properties) we can:

1) transform the expecations of a sum into a sum of expecations
2) move the $\Lambda$ out of the expecatios, as it doesn't depend on t 
3) $\langle z_{:,t} \epsilon_t \rangle = \langle z_{:,t} \rangle \langle \epsilon_t \rangle$ because $z_{:,t}$ and $\epsilon_t$ are independent random variables

$\langle x_{:,t}x_{:,t}^T \rangle = \Lambda \langle z_{:,t} z_{:,t}^T\rangle \Lambda^T + \Lambda \langle z_{:,t} \rangle \langle \epsilon_{t}^T \rangle + \langle \epsilon_{t} \rangle \Lambda^T \langle z_{:,t}^T  \rangle + \langle \epsilon_t \epsilon_{t}^T \rangle$

Then considering that $\langle z_{:,t} \rangle = 0$ and that $\langle \epsilon_t \rangle = 0$
the expression can be simplified as:

$\langle x_{:,t}x_{:,t \prime}^T \rangle = \Lambda \langle z_{:,t} z_{:,t \prime}^T\rangle \Lambda^T + \langle \epsilon_t \epsilon_{t \prime}^T \rangle$

Then substituting:
1) $\langle z_{:,t} z_{:,t \prime}^T\rangle = k(t,t \prime)$ as that is the covariance matrix of the Gaussian process
2) $\langle \epsilon_t \epsilon_{t \prime}^T \rangle= 0$ as $\epsilon_t$ and $\epsilon_{t \prime}$ are independent and $\langle \epsilon_t \rangle = 0$

$\langle x_{:,t}x_{:,t \prime}^T \rangle = \Lambda k(t,t \prime) \Lambda^T$


### Result

The equation for the diagonal and off-diagonal element can be summarized as:

$$\langle x_{:,t}x_{:,t \prime}^T \rangle = \Lambda k(t,t \prime) \Lambda^T + \delta(t - t \prime)\psi$$

where $\delta(x) = \begin{cases}
                1 & if\ x=0 \\
                0    & if\ x \ne 0 \\
            \end{cases}$ 

Therefore $p(X)$ can be modelled as:

$$p(X) = \mathcal{N}\left (0 , {\begin{array}{cccc}
    \Lambda k(t_1,t_1) \Lambda^T + \delta(1-1)\psi & \Lambda k(t_{1},t_{2}) \Lambda^T + \delta(1-2)\psi& \cdots & \Lambda k(t_1 ,t_t) \Lambda^T + \delta(1-t)\psi\\
    \Lambda k(t_{2},t_{1}) \Lambda^T+ \delta(2-1)\psi &  \Lambda k(t_{2},t_{2}) \Lambda^T + \delta(2-2)\psi & \cdots & \Lambda k(t_{2},t_{t}) \Lambda^T + \delta(2-t)\psi\\
    \vdots & \vdots & \ddots & \vdots\\
    \Lambda k(t_{t}, t_{1}) \Lambda^T+ \delta(t-1)\psi & \Lambda k(t_{t},t_{2}) \Lambda^T + \delta(t-2)\psi& \cdots & \Lambda k(t_{t},t_{t}) \Lambda^T + \delta(t-t)\psi\\
    \end{array} } \right )$$

and this is also Gaussian Process with a "special" kernel. Multiplying kernel with a constant ($\Lambda$) or adding a kernel ($\delta$) yields another valid kernel


If we define a new kernel as $$K(t,t \prime) = \Lambda k(t,t \prime) \Lambda^T + \delta(t - t \prime)\psi$$

Then

$$ p(X) = \mathcal{GP}(0, K(t, t\prime))$$

## Next steps

- The parameters of the final GP ($\Lambda, \psi$ and the kernel hyperparameters) can be fitted by maximizing the likelihood of $p(X)$ using gradient descent

# Implementation

In [ ]:
#| export
import torch
import gpytorch

## Kernel

In [ ]:
#| export
class GPFAKernel(gpytorch.kernels.Kernel):
    """
    Kernel to implement Gaussian Processes Factor Analysis
    """
    def __init__(self, n_features: int, latent_kernel: gpytorch.kernels.Kernel, latent_dims = 1, Lambda: torch.tensor = None, psi: torch.tensor = None, **kwargs):
        """
        :n_features: number of variables at each time step
        :latent_kernel: any valid GPyTorch Kernel used to model the relationship over time of the latent
        :latent_dims: Number of latent dims, for now only 1 supported
        :Lambda: (n_features * latent_dims) initial value for factor loading matrix
        :psi: (n_features) initial value for random noise covariance. Note this is only the diagonal matrix
        """
        super(GPFAKernel, self).__init__(**kwargs)
        
        # Number of features in the X for each time step
        self.n_features = n_features
        assert latent_dims == 1 # Not implemented yet
        self.latent_dims = latent_dims
        
        # see GPyTorch Kernels
        self.register_parameter(
            name = "Lambda",
            parameter = torch.nn.Parameter(torch.ones(self.n_features, self.latent_dims)))
        
        self.latent_kernel = latent_kernel
        
        self.register_parameter(
            name = "raw_psi_diag",
            parameter = torch.nn.Parameter(torch.zeros(self.n_features))) 
        self.register_constraint("raw_psi_diag", gpytorch.constraints.Positive())
        if psi is not None: self.psi = psi
    
    # Convenient getter and setter for psi, since there is the Positive() constraint
    @property
    def psi(self):
        # when accessing the parameter, apply the constraint transform
        return self.raw_psi_diag_constraint.transform(self.raw_psi_diag)

    @psi.setter
    def psi(self, value):
        return self._set_psi(value)

    def _set_psi(self, value):
        if not torch.is_tensor(value):
            value = torch.as_tensor(value).to(self.raw_psi_diag)
        # when setting the paramater, transform the actual value to a raw one by applying the inverse transform
        self.initialize(raw_psi_diag=self.raw_psi_diag_constraint.inverse_transform(value))
    

        
    # perform the actual calculation
    def forward(self, t1, t2, diag = False, last_dim_is_batch=False, **params):

        # not implemented yet
        assert diag is False
        assert last_dim_is_batch is False

        # take the number of observations from the input
        n_obs = t1.shape[0]

        # compute the latent kernel
        kT = self.latent_kernel(t1, t2, diag, last_dim_is_batch, **params).evaluate() # this may make the whole thing slow
       
        return compute_gpfa_covariance(self.Lambda, kT, self.psi, self.n_features, n_obs)
    
    def num_outputs_per_input(self, x1,x2):
        return self.n_features

# this is a separate function, because torch script cannot take self as a parameter
@torch.jit.script
def compute_gpfa_covariance(Lambda, kT, psi, n_features, n_obs):
    # pre allocate covariance matrix
    X_cov = torch.empty(n_features * n_obs, n_features * n_obs)
    for i in torch.arange(n_obs):
        for j in torch.arange(n_obs):
            # i:i+1 is required to keep the number of dimensions
            cov =  Lambda @ kT[i:i+1,j:j+1] @ Lambda.T
            # only diagonals add the noise
            if i == j: cov += torch.diag(psi)
            # add a block of size n_features*n_features to the covariance matrix
            X_cov[i*n_features:(i*n_features + n_features),j*n_features:(j*n_features+n_features)] = cov
    return X_cov

In [ ]:
gpfa_k = GPFAKernel(n_features=2, latent_kernel=gpytorch.kernels.RBFKernel())

The parameters are correctly registered

In [ ]:
list(gpfa_k.named_parameters())

[('Lambda',
  Parameter containing:
  tensor([[1.],
          [1.]], requires_grad=True)),
 ('raw_psi_diag',
  Parameter containing:
  tensor([0., 0.], requires_grad=True)),
 ('latent_kernel.raw_lengthscale',
  Parameter containing:
  tensor([[0.]], requires_grad=True))]

Check that the Kernel is running

In [ ]:
gpfa_k(torch.tensor((1, 2, 3))).evaluate()

tensor([[1.6931, 1.0000, 0.3532, 0.3532, 0.0156, 0.0156],
        [1.0000, 1.6931, 0.3532, 0.3532, 0.0156, 0.0156],
        [0.3532, 0.3532, 1.6931, 1.0000, 0.3532, 0.3532],
        [0.3532, 0.3532, 1.0000, 1.6931, 0.3532, 0.3532],
        [0.0156, 0.0156, 0.3532, 0.3532, 1.6931, 1.0000],
        [0.0156, 0.0156, 0.3532, 0.3532, 1.0000, 1.6931]],
       grad_fn=<CopySlices>)

## GPFA 

In [ ]:
#| export
class GPFAZeroMean(gpytorch.means.Mean):
    """
    Zero Mean function to be used in GPFA, as it takes into account the number of features
    """
    def __init__(self, n_features):
        super().__init__()
        self.n_features = n_features
    def forward(self, input):
        shape = input.shape[0] * self.n_features
        return torch.zeros(shape)

In [ ]:
#| export
class GPFA(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, n_features, latent_kernel):
        super(GPFA, self).__init__(train_x, train_y, likelihood)
        self.mean_module = GPFAZeroMean(n_features)
        self.covar_module = GPFAKernel(n_features, latent_kernel)

    def forward(self, x, **params):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x, **params)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

make some very simple test data, to check that the model is working and can learn the parameters

In [ ]:
T = torch.arange(1,5)

In [ ]:
X = torch.hstack([torch.arange(0,3) + 2* i for i in T]) 

In [ ]:
X

tensor([ 2,  3,  4,  4,  5,  6,  6,  7,  8,  8,  9, 10])

In [ ]:
X.shape

torch.Size([12])

In [ ]:
T

tensor([1, 2, 3, 4])

In [ ]:
# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = GPFA(T, X, likelihood, n_features = 3, latent_kernel = gpytorch.kernels.RBFKernel())

In [ ]:
model

GPFA(
  (likelihood): GaussianLikelihood(
    (noise_covar): HomoskedasticNoise(
      (raw_noise_constraint): GreaterThan(1.000E-04)
    )
  )
  (mean_module): GPFAZeroMean()
  (covar_module): GPFAKernel(
    (latent_kernel): RBFKernel(
      (raw_lengthscale_constraint): Positive()
    )
    (raw_psi_diag_constraint): Positive()
  )
)

Getting the prior from the GP

In [ ]:
model(T)

MultivariateNormal(loc: torch.Size([12]))

Fitting the parameters using gradient descend

In [ ]:
# this is for running the notebook in our testing framework
training_iter = 10

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
losses = []
for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(T)
    # Calc loss and backprop gradients
    loss = -mll(output, X)
    losses.append(loss.item())
    loss.backward()
    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f, Lambda: %.3f   noise: %.3f' % (
        i + 1, training_iter, loss.item(),
        model.covar_module.latent_kernel.lengthscale.item(),
        model.covar_module.Lambda.mean().item(),
        model.likelihood.noise.item()
    ))
    optimizer.step()

Iter 1/10 - Loss: 2.500   lengthscale: 1.240, Lambda: 1.809   noise: 1.053
Iter 2/10 - Loss: 2.392   lengthscale: 1.312, Lambda: 1.909   noise: 0.989
Iter 3/10 - Loss: 2.296   lengthscale: 1.386, Lambda: 1.985   noise: 0.927
Iter 4/10 - Loss: 2.211   lengthscale: 1.460, Lambda: 2.065   noise: 0.868
Iter 5/10 - Loss: 2.133   lengthscale: 1.535, Lambda: 2.147   noise: 0.811
Iter 6/10 - Loss: 2.062   lengthscale: 1.611, Lambda: 2.227   noise: 0.756
Iter 7/10 - Loss: 1.996   lengthscale: 1.686, Lambda: 2.300   noise: 0.703
Iter 8/10 - Loss: 1.934   lengthscale: 1.761, Lambda: 2.364   noise: 0.653
Iter 9/10 - Loss: 1.876   lengthscale: 1.835, Lambda: 2.424   noise: 0.606
Iter 10/10 - Loss: 1.822   lengthscale: 1.908, Lambda: 2.485   noise: 0.560


The model is training!

Still missing:

- multiple latent dimensions
- batches in GPyTorch
- proper optimization (writing a for loop in python is a no go)

In [ ]:
#| hide
from nbdev import nbdev_export
nbdev_export()